### ISSUE TITLE
V-motion animations doesn't work

### ISSUE THREAD

**Issue by Sunflowerdevsw** [anaskhonprime/personal.github.io#3]
How can i use  v-motion animation tag? My code similar with u, but it does't work

**Comment by anaskhonprime** [comment]
Good evening, for using  v-motion, you need install and set main.js

[ Oficial Documentation ] 

1. install @vueuse/motion

`npm add @vueuse/motion`

2. set  src/main.js

`import { MotionPlugin } from '@vueuse/motion'

const app = createApp(App)

app.use(MotionPlugin)

app.mount('#app')`

i hope it will work^^
